# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_finance_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('invited_family', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'To invite'), ('1', 'Invited'), ('2', 'Confirmed'), ('3', 'Not yet confirmed')], default='1', max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Invited',
        ),
    ]
