# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_buffet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buffet',
            name='id',
        ),
        migrations.AlterField(
            model_name='buffet',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, primary_key=True, serialize=False),
        ),
    ]
