# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20170928_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffet',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buffet',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
