# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20170928_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
